In [2]:
from pandas import read_csv

dataframe = read_csv('processed_data.csv')

In [5]:
dataframe.tail(100)

,Unnamed: 0,date,time,account,interface,sourceIP,destIP,srcPort,dstPort,protocol,packets,byte,startTime,timeTook,status,Cattemptlastsec,Rlastsec
801075,813000,2021-02-10,2021-07-03 21:12:40,430405884063,eni-0f1ef81b7d2bc701d,194.147.140.60,172.16.1.173,51467,55500,6,1,40,1612991560,60,0,9.0,9.0
801076,813001,2021-02-10,2021-07-03 21:12:40,430405884063,eni-0f1ef81b7d2bc701d,172.16.1.173,172.16.1.144,8080,20910,6,5,561,1612991560,60,1,869.0,NaN
801077,813002,2021-02-10,2021-07-03 21:12:40,430405884063,eni-0f1ef81b7d2bc701d,172.16.1.144,172.16.1.173,20910,8080,6,5,400,1612991560,60,1,111.0,NaN
801078,813003,2021-02-10,2021-07-03 21:12:40,430405884063,eni-0f1ef81b7d2bc701d,172.16.1.173,52.46.147.133,39214,443,6,25,7987,1612991560,60,1,870.0,NaN
801079,813004,2021-02-10,2021-07-03 21:12:40,430405884063,eni-0f1ef81b7d2bc701d,52.46.147.133,172.16.1.173,443,39214,6,23,7501,1612991560,60,1,5.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
801170,813095,2021-02-10,2021-07-03 23:59:58,430405884063,eni-0638b7eb0241d0a58,13.72.67.143,172.16.1.36,34198,443,6,9,1606,1613001598,8,1,14.0,NaN
801171,813096,2021-02-10,2021-07-03 23:59:58,430405884063,eni-0638b7eb0241d0a58,172.16.1.36,13.72.67.143,443,34198,6,15,12271,1613001598,8,1,36.0,NaN
801172,813097,2021-02-10,2021-07-03 23:59:58,430405884063,eni-0638b7eb0241d0a58,172.16.1.250,172.16.1.36,80,63046,6,1,52,1613001598,8,1,7.0,NaN
801173,813098,2021-02-10,2021-07-03 23:59:58,430405884063,eni-0638b7eb0241d0a58,172.16.1.36,172.16.1.250,63046,80,6,2,104,1613001598,8,1,20.0,NaN
801174,813099,2021-02-10,2021-07-03 23:59:56,430405884063,eni-0638b7eb0241d0a58,172.16.1.250,172.16.1.36,80,63096,6,3,295,1613001596,1,1,5.0,NaN

In [39]:
from numpy import nan
df = dataframe
df['Rlastsec'] = df['Rlastsec'].fillna(0)
df['is_attack'] = nan
df['is_attack'] = (df['Cattemptlastsec'] > 1000) | (df['Rlastsec'] > 3) # This is our rule for our data!

# This is our dataset to train, tweak, and test our model on.
X = df.loc[:, ['Cattemptlastsec', 'Rlastsec']]
Y = df['is_attack'].astype(int)

datalength = len(Y)
x_train = X.loc[:int(datalength*.7)] # however many rows are 70% of the data
y_train = Y.loc[:int(datalength*.7)] # however many rows are 70% of the data

x_cv = X.loc[int(datalength*.7):int(datalength*.9)] # the rows between the 70 % mark and the 90% mark
y_cv = Y.loc[int(datalength*.7):int(datalength*.9)] # the rows between the 70 % mark and the 90% mark

x_test = X.loc[int(datalength*.9):] # however many rows are last 10% of the data
y_test = Y.loc[int(datalength*.9):] # however many rows are last 10% of the data

from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(random_state=0, verbose=1).fit(x_train, y_train)
clf.predict(x_cv[:2])
#clf.predict_proba(X[:2, :])
clf.score(x_train, y_train)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    3.4s finished

1.0

In [42]:


#df[df['is_attack']==1]

1.0

In [34]:
print(x_test.count())
print(x_test[x_test['Cattemptlastsec'] < j1000].count())

Cattemptlastsec    80118
Rlastsec           80118
dtype: int64
Cattemptlastsec    55699
Rlastsec           55699
dtype: int64